server:
  port: 1003
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
spring:
  application:
    name: order-feign

    thymeleaf:
      encoding: UTF-8
      servlet:
        content-type: text/html
