server:
  port: 1003
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
spring:
  application:
    name: order-feign
  thymeleaf:
    content-type: text/html
    cache: false
    mode: LEGACYHTML5
  #给指定包下面的类起别名
  type-aliases-package: com.jk.pojo

