server:
  port: 1002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
spring:
  application:
    name: service-provider
  datasource:
    name: mydb
    url: jdbc:mysql://192.168.101.55:3306/drug?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapperLocations: classpath*:mybatis/mapper-*.xml
  #给指定包下面的类起别名
  type-aliases-package: com.jk.pojo

  #pagehelper分页插件配置
  pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params:
      params:
        count: countSql
